export default {
  youtube: {
    channels: []
  },
  features: ['home'],
  translations: {
    'Images of “{text}” on the Web': 'Images of “{text}” on the Web',
    'Collocations with “{ text }”': 'Collocations with “{ text }”',
    copyPasteCSV: '<b>Copy</b> the text below and <b>paste</b> into your spreadsheet program, or a flashcard app like Anki or Quizlet.',
    textReaderIntro: 'Write or paste in some English text, and annotated text will show up below the textbox. You can also use <b>Markdown or HTML tags</b>. Everything is autosaved to your browser’s <code>localStorage</code>, so even if you refresh your browser everything you entered is still here.',
    libraryIntro: 'Read books from various English sources directly in our <a href="#/{lang}/library">Library</a>.',
    'Collocations with “{text}”': 'Collocations with “{text}”',
    'Sentences with “{text}”': 'Sentences with “{text}”',
    '“{text}” videos on YouTube': '“{text}” videos on YouTube',
    'Collocations provided by': 'Collocations provided by',
    'Sentences provided by': 'Sentences provided by',
    'Search for more sentences at': 'Search for more sentences at',
    '"{word}" and/or ...': '"{word}" and/or ...',
    'nouns modified by "{word}"': 'nouns modified by "{word}"',
    'objects of "{word}"': 'Objects of "{word}"',
    'subjects of "{word}"': '"Subjects of "{word}',
    'prepositional phrases': '介词短语',
    'pronominal objects of "{word}"': 'Pronominal objects of "{word}"',
    'verbs with "{word}" as object': 'Verbs with "{word}" as object',
    'verbs with "{word}" as subject': 'Verbs with "{word}" as subject',
    'adjective predicates of "{word}"': 'Adjective predicates of "{word}"',
    '"{word}" is a ...': '"{word}" is a ...',
    '{word}\'s ...': '{word}\'s ...',
    'possessors of "{word}"': 'Possessors of "{word}"',
    'pronominal possessors of "{word}"': 'Pronominal possessors of "{word}"',
    'usage patterns': 'Usage patterns',
    '... is a "{word}"': '... is a "{word}"',
    'verbs with particle "up" and "{word}" as object': 'Verbs with particle "up" and "{word}" as object',
    'verbs with particle "out" and "{word}" as object': 'Verbs with particle "out" and "{word}" as object',
    'verbs with particle "down" and "{word}" as object': 'Verbs with particle "down" and "{word}" as object',
    'verbs with particle "off" and "{word}" as object': 'Verbs with particle "off" and "{word}" as object',
    'verbs with particle "over" and "{word}" as object': 'Verbs with particle "over" and "{word}" as object',
    'modifiers of "{word}"': 'Modifiers of "{word}"',
    'infinitive objects of "{word}"': 'Infinitive objects of "{word}"',
    'verbs complemented by "{word}"': 'Verbs complemented by "{word}"',
    'verbs before "{word}"': 'Verbs before "{word}"',
    'subjects of "be {word}"': 'Subjects of "be {word}"',
    'verbs with particle "away" and "{word}" as object': 'Verbs with particle "away" and "{word}" as object'
  }
}
  