export default {
  youtube: {
    channels: []
  },
  features: ['home'],
  translations: {
    'Learn varous languages through English:': '通过英语学习其他语言：',
    'Learn English through various languages:': '让全世界学习英语：',
    'Dictionary': '词典',
    'Reading': '阅读材料',
    'Audio-Visual': '视听资源',
    'Settings': '设置',
    'Lookup Words': '查词',
    'Saved': '生词本',
    'For the love of English words.': '只因酷爱英文词。',
    'Look up words here...': '输入英文单词……',
    'Random': '随机',
    'Images of “{text}” on the Web': '网上关于 “{text}” 的图片',
    'Image search by': '图片搜索提供方',
    'Collocations with “{text}”': '跟 “{text}” 的词语搭配',
    'Sentences with “{text}”': '有 “{text}” 的句子',
    '“{text}” videos on YouTube': '在 YouTube 上关于 “{text}” 的视频',
    'Collocations provided by': '词语搭配提供方',
    'Sentences provided by': '例句提供方',
    'Search for more sentences at': '用其他服务搜索更多例句',
    '"{word}" and/or ...': '"{word}" 的并列搭配',
    'nouns modified by "{word}"': '"{word}" 修饰的名词',
    'objects of "{word}"': '"{word}" 的宾语', 
    'subjects of "{word}"': '"{word}" 的主语', 
    'prepositional phrases': '介词短语', 
    'pronominal objects of "{word}"': '"{word}" 的宾语代词', 
    'verbs with "{word}" as object': '以 "{word}" 为宾语的动词', 
    'verbs with "{word}" as subject': '以 "{word}" 为主语的动词', 
    'adjective predicates of "{word}"': '"{word}" 的形容词谓语', 
    '"{word}" is a ...': '"{word}" is a ...', 
    '{word}\'s ...': '{word}\'s ...', 
    'possessors of "{word}"': '"{word}" 的所属', 
    'pronominal possessors of "{word}"': '"{word}" 的所属代词', 
    'usage patterns': '使用模式', 
    '... is a "{word}"': '... is a "{word}"', 
    'verbs with particle "up" and "{word}" as object': '动词 + up {word}', 
    'verbs with particle "out" and "{word}" as object': '动词 + out {word}', 
    'verbs with particle "down" and "{word}" as object': '动词 + down {word}', 
    'verbs with particle "off" and "{word}" as object': '动词 + off {word}', 
    'verbs with particle "over" and "{word}" as object': '动词 + over {word}', 
    'modifiers of "{word}"': '修饰 "{word}" 的词', 
    'infinitive objects of "{word}"': '"{word}" 的不定式宾语', 
    'verbs complemented by "{word}"': '以 "{word}" 为补语的动词', 
    'verbs before "{word}"': '在 "{word}" 之前的动词', 
    'subjects of "be {word}"': '"be {word}" 的主语', 
    'verbs with particle "away" and "{word}" as object': '动词 + away {word}'
  }
}
