export default {
  youtube: {
    channels: []
  },
  features: ['home'],
  translations: {
    'Learn varous languages through English:': '通过英语学习其他语言：',
    'Learn English through various languages:': '让全世界学习英语：',
    Dictionary: '词典',
    Reading: '阅读材料',
    'Audio-Visual': '视听资源',
    Settings: '设置',
    'Lookup Words': '查词',
    Saved: '生词本',
    'For the love of English words.': '只因酷爱英文词。',
    'Look up words here...': '输入英文单词……',
    Random: '随机',
    'Images of “{text}” on the Web': '网上关于 “{text}” 的图片',
    'Image search by': '图片搜索提供方',
    'Collocations with “{text}”': '跟 “{text}” 的词语搭配',
    'Sentences with “{text}”': '有 “{text}” 的句子',
    '“{text}” videos on YouTube': '在 YouTube 上关于 “{text}” 的视频',
    'Collocations provided by': '词语搭配提供方',
    'Sentences provided by': '例句提供方',
    'Search for more sentences at': '用其他服务搜索更多例句',
    '"{word}" and/or ...': '"{word}" 的并列搭配',
    'nouns modified by "{word}"': '"{word}" 修饰的名词',
    'objects of "{word}"': '"{word}" 的宾语',
    'subjects of "{word}"': '"{word}" 的主语',
    'prepositional phrases': '介词短语',
    'pronominal objects of "{word}"': '"{word}" 的宾语代词',
    'verbs with "{word}" as object': '以 "{word}" 为宾语的动词',
    'verbs with "{word}" as subject': '以 "{word}" 为主语的动词',
    'adjective predicates of "{word}"': '"{word}" 的形容词谓语',
    '"{word}" is a ...': '"{word}" is a ...',
    '{word}\'s ...': '{word}\'s ...',
    'possessors of "{word}"': '"{word}" 的所属',
    'pronominal possessors of "{word}"': '"{word}" 的所属代词',
    'usage patterns': '使用模式',
    '... is a "{word}"': '... is a "{word}"',
    'verbs with particle "up" and "{word}" as object': '动词 + up {word}',
    'verbs with particle "out" and "{word}" as object': '动词 + out {word}',
    'verbs with particle "down" and "{word}" as object': '动词 + down {word}',
    'verbs with particle "off" and "{word}" as object': '动词 + off {word}',
    'verbs with particle "over" and "{word}" as object': '动词 + over {word}',
    'modifiers of "{word}"': '修饰 "{word}" 的词',
    'infinitive objects of "{word}"': '"{word}" 的不定式宾语',
    'verbs complemented by "{word}"': '以 "{word}" 为补语的动词',
    'verbs before "{word}"': '在 "{word}" 之前的动词',
    'subjects of "be {word}"': '"be {word}" 的主语',
    'verbs with particle "away" and "{word}" as object': '动词 + away {word}',
    'My Words': '生词本',
    'These words are stored in your browser\'s local storage, which persists unless you clear your browsing data.':
      '这些单词将存储于浏览器的本地存储（local storage）中。除非您清除浏览数据，否则该存储会持续保留。',
    'Export CSV': '导出 CSV 文件',
    'Clear': '清除',
    'Inlcude:': '包括：',
    'copyPasteCSV': 
    '将下面的文本<b>复制</b>并<b>粘贴</b>到电子表格程序中，或导入到类似 Anki 或 Quizlet 的背单词程序中。',
    'English': '英语',
    'Pronunciation': '发音',
    'Definitions': '释义',
    'Text Reader': '文本阅读器',
    'textReaderIntro': '在一些英文文本中书写或粘贴，带注释的文本将显示在文本框下方。您也可以使用<b>Markdown</b>或<b>HTML</b>标签。所有内容都会自动保存到浏览器的 <code>localstorage</code> 里，因此即使刷新浏览器，输入的所有内容仍会保留在此。',
    'Enter your English text here. Markdown and HTML also supported.': '在此键入英文文本。同时支持 Markdown 和 HTML。',
    'Not sure what to read?': '不知道该读什么吗？',
    'Try these resources:': '试试以下资源',
    'Look for English music lyrics on Google.': '使用搜索引擎查找英文歌词。',
    libraryIntro: '在 “<a href="#/{lang}/library">阅览室</a>” 页面直接阅读各式英文文献。',
    'YouTube Transcript': '学习 YouTube 字幕',
    'Library': '阅览室',
    'This is where you can enjoy reading a variety of English books with the help of hover dictionary and the ability to save words.': '在这里，你可以借助光标取词词典阅读各种英语书籍。点击任何英语单词，将其存入单词表，之后可前往“词典 > 单词表”查看。',
    'Custom Reading': '自定义阅读',
    'Read any online document by pasting the URL.': '粘贴网址，阅读任意网上文章。'
  }
}
